defaults:
  - model: mixtral
  - training: default
  - data_mixture: single
  - preprocessing: default
  - experiment: null
  - _self_

wandb:
  project: finetuning
  name: ${model.name}-${training.learning_rate}
